'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowDown, Menu, X, MapPin, Phone } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { business as b, photos } from './data';
const nav = [['Home', '#home'], ['Collections', '#collections'], ['About', '#about'], ['Gallery', '#gallery'], ['Visit Us', '#visit']];
export function Picture({ photo, className = '', eager = false }: { photo: {src: string; alt: string}; className?: string; eager?: boolean }) { return <img className={className} src={photo.src} srcSet={[400,800,1200].map(w => `${photo.src.replace("-1200.webp", `-${w}.webp`)} ${w}w`).join(", ")} sizes="(max-width: 767px) 100vw, 60vw" alt={photo.alt} loading={eager ? 'eager' : 'lazy'} fetchPriority={eager ? 'high' : 'auto'} />; }
export function Directions({ children = 'Get Directions', className = '' }: {children?: React.ReactNode; className?: string}) { return <a className={`action ${className}`} href={b.mapsUrl} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={18}/></a>; }
export function Logo() { return <a className="logo" href="#home" aria-label="Mr.Clothing unisex home">MR.CLOTHING<span>U N I S E X</span></a>; }
export function Navbar() {
 const [open,setOpen] = useState(false); const [scrolled,setScrolled] = useState(false); const toggle = useRef<HTMLButtonElement>(null);
 useEffect(()=>{ const scroll=()=>setScrolled(window.scrollY>25); scroll(); window.addEventListener('scroll',scroll,{passive:true}); return ()=>window.removeEventListener('scroll',scroll);},[]);
 return <header className={`header ${scrolled?'scrolled':''}`} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);toggle.current?.focus();}}}><Logo/><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([name,url])=><a key={name} href={url}>{name}</a>)}</nav><Directions className="nav-cta"/><Button ref={toggle} className="menu-toggle" variant="ghost" aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} aria-controls="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button>{open&&<nav id="mobile-menu" className="mobile-menu" aria-label="Mobile navigation">{nav.map(([name,url],i)=><a key={name} href={url} onClick={()=>setOpen(false)}><small>0{i+1}</small>{name}<ArrowUpRight/></a>)}<Directions/></nav>}</header>;
}
export function Hero(){return <section className="hero" id="home"><div className="hero-copy"><p className="eyebrow"><span className="dot"/> UNISEX FASHION · BENGALURU</p><h1>Style that<br/>speaks<br/>for <em>you.</em></h1><p className="hero-description">Discover everyday fashion and fresh styles at Mr.Clothing unisex in Bengaluru.</p><div className="hero-actions"><a className="action dark" href="#collections">Explore Collection <ArrowUpRight size={18}/></a><Directions className="text-action">Visit Our Store</Directions></div><div className="hero-bottom"><span><b>★ {b.rating}</b> Google Rating</span><a href="#collections" aria-label="Scroll to collections"><ArrowDown size={17}/> SCROLL TO DISCOVER</a></div></div><div className="hero-image"><Picture photo={photos.hero} eager/><div className="image-top"><span>THE EVERYDAY EDIT</span><span>01 / 05</span></div><div className="hero-image-caption"><span>Wear it your way.</span><ArrowUpRight size={46}/></div><span className="photo-label">EDITORIAL INSPIRATION</span></div></section>}
export function MobileActions(){return <div className="mobile-actions"><a href={b.tel}><Phone size={17}/>Call Store</a><a href={b.mapsUrl} target="_blank" rel="noopener noreferrer"><MapPin size={17}/>Get Directions</a></div>}
