import { ArrowUpRight, ArrowDown, MapPin, Phone, Clock, MoveUpRight, Star } from 'lucide-react';
import { Navbar, Hero, Picture, Directions, Logo, MobileActions } from './components';
import { business as b, photos, galleryImages } from './data';
const collections = [
 {title:"Men’s style",note:'A little attitude. A lot of you.',photo:photos.men},
 {title:'Men’s accessories',note:'The finishing touches matter.',photo:photos.accessories},
 {title:'Casual wear',note:'Off-duty. On your terms.',photo:photos.casual},
 {title:'Perfume',note:'A signature that stays with you.',photo:photos.perfume},
];
const features = [
 ['01','Unisex fashion','Different tastes. Individual expression. Everyday wardrobes.'],
 ['02','In your neighbourhood','Find us in Chokkanahalli, near Bhartiya City, Bengaluru.'],
 ['03','On your schedule',`Open every day, ${b.hours}. Drop by when it suits you.`],
 ['04','Locally loved',`Rated ${b.rating}/5 on Google, based on ${b.reviewCount} currently listed reviews.`],
];
const schema = {'@context':'https://schema.org','@type':'ClothingStore',name:b.name,telephone:b.phone,address:{'@type':'PostalAddress',streetAddress:'No. 30, Bhartiya City, opposite ICICI Manipal, Yelanka, Chokkanahalli',addressLocality:'Bengaluru',addressRegion:'Karnataka',postalCode:'560064',addressCountry:'IN'},openingHours:'Mo-Su 09:30-23:30',aggregateRating:{'@type':'AggregateRating',ratingValue:b.rating,reviewCount:b.reviewCount},hasMap:b.mapsUrl};
export default function Home(){return <>
 <a className="skip-link" href="#main">Skip to content</a><Navbar/>
 <main id="main"><Hero/>
 <section className="info-strip" aria-label="Store at a glance"><div><Star size={18}/><p><strong>{b.rating} / 5</strong><span>Google Rating</span></p></div><div><Clock size={18}/><p><strong>Open Daily</strong><span>{b.hours}</span></p></div><div><MapPin size={18}/><p><strong>Bengaluru</strong><span>Chokkanahalli</span></p></div><a href={b.tel}><Phone size={18}/><p><strong>Call Us</strong><span>{b.phone}</span></p></a></section>
 <section className="section collections" id="collections"><div className="section-heading"><div><p className="eyebrow">01 / THE STYLE EDIT</p><h2>Find your <em>style.</em></h2></div><p>Different moods. Different moments.<br/>Always, unapologetically you.</p></div>
 <div className="collection-grid">{collections.map((c,i)=><a className={`collection-card collection-${i}`} href="#visit" key={c.title}><div className="collection-image"><Picture photo={c.photo}/><span className="image-index">0{i+1}</span><span className="circle-arrow"><ArrowUpRight size={22}/></span></div><div className="collection-caption"><h3>{c.title}</h3><p>{c.note}</p></div></a>)}<a href="#visit" className="new-styles"><span className="eyebrow">05 / A FRESH PERSPECTIVE</span><h3>New styles.<br/>New possibilities.</h3><span>Find your next look in-store <ArrowUpRight size={19}/></span><span className="large-asterisk" aria-hidden="true">✳</span></a></div>
 <p className="editorial-note">A little inspiration for your next visit. Images illustrate style categories, not current store inventory.</p></section>
 <section className="about section" id="about"><div className="about-image"><Picture photo={photos.detail}/><span className="vertical-caption">THE DETAILS MAKE THE DIFFERENCE</span><span className="about-image-note">EDITORIAL PHOTOGRAPHY</span></div><div className="about-copy"><p className="eyebrow">02 / HELLO, NEIGHBOUR</p><h2>Fashion for<br/>every <em>day.</em></h2><p>Mr.Clothing unisex is a local clothing destination in Bengaluru for customers looking to refresh their everyday style. Conveniently located in Chokkanahalli near Bhartiya City, the store offers an easy way to explore fashion locally and find a look that works for you.</p><div className="brand-manifesto">Your style.<br/>Your choice.<br/><span>Your store.</span></div><Directions className="text-action">Meet us in-store</Directions></div></section>
 <section className="features section"><div className="section-heading"><div><p className="eyebrow">GOOD STYLE. CLOSE TO HOME.</p><h2>Your local fashion stop.</h2></div></div><div className="feature-grid">{features.map(([n,title,copy])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
 <section className="gallery section" id="gallery"><div className="section-heading"><div><p className="eyebrow">03 / THE MOODBOARD</p><h2>Inside <em>Mr.Clothing.</em></h2></div><p>A feeling. A texture. A way to wear it.<br/>A glimpse of the style that inspires us.</p></div><div className="gallery-grid">{galleryImages.map((photo,i)=><figure key={photo.src} className={`gallery-item gallery-${i}`}><Picture photo={photo}/><figcaption><span>0{i+1}</span>{['Spaces & inspiration','Street perspective','Soft textures','Style in motion','On the rail','Out & about'][i]}</figcaption></figure>)}</div><p className="editorial-note">Our inspiration board — reference fashion and interior photography. Actual Mr.Clothing store photographs coming when supplied.</p></section>
 <section className="rating section"><div className="rating-intro"><p className="eyebrow">A LITTLE LOCAL LOVE</p><h2>Good style.<br/><em>Good company.</em></h2><p>Rated by customers on Google.</p><Directions className="text-action">View on Google Maps</Directions></div><div className="rating-number"><div><strong>{b.rating}</strong><span>/ 5</span></div><p className="stars" aria-label="Five star rating illustration">★★★★★</p><p>Google Rating</p><small>Based on {b.reviewCount} currently listed reviews</small></div></section>
 <section className="visit section" id="visit"><div className="section-heading"><div><p className="eyebrow">04 / SEE YOU IN STORE</p><h2>Come find<br/>your next <em>look.</em></h2></div><p>Visit Mr.Clothing unisex<br/>in Chokkanahalli, Bengaluru.</p></div><div className="visit-grid"><div className="store-details"><div><MapPin size={19}/><div><h3>MR.CLOTHING UNISEX</h3><address>{b.address}</address></div></div><div><Clock size={19}/><div><h3>OPEN EVERY DAY</h3><p>Monday – Sunday<br/>{b.hours}</p></div></div><div><Phone size={19}/><div><h3>GIVE US A CALL</h3><a className="phone-link" href={b.tel}>{b.phone}</a></div></div><div className="visit-actions"><Directions className="dark"/><a className="action" href={b.tel}>Call Store <Phone size={16}/></a></div></div><a className="location-card" href={b.mapsUrl} target="_blank" rel="noopener noreferrer"><div className="location-card-top"><span className="eyebrow">YOUR NEXT STOP</span><ArrowUpRight size={27}/></div><div className="location-center"><MapPin size={45} strokeWidth={1}/><h3>Find us in<br/><em>Bengaluru.</em></h3><p>Chokkanahalli · Near Bhartiya City</p></div><div className="location-card-bottom"><span>Mr.Clothing unisex</span><span>Open in Google Maps <ArrowUpRight size={15}/></span></div></a></div></section>
 <section className="final-cta"><Picture photo={photos.casual}/><div><p className="eyebrow">MAKE IT PERSONAL</p><h2>Your next look<br/>is <em>waiting.</em></h2><p>Visit Mr.Clothing unisex in Bengaluru.</p><div className="final-actions"><Directions/><a href={b.tel} className="action">Call {b.phone}<Phone size={16}/></a></div></div><span className="final-photo-note">EDITORIAL INSPIRATION</span></section>
 </main><footer className="footer"><div className="footer-top"><div><Logo/><p>Everyday style in Bengaluru.</p></div><nav aria-label="Footer navigation">{[['Home','home'],['Collections','collections'],['About','about'],['Gallery','gallery'],['Visit Us','visit']].map(([label,id])=><a key={id} href={`#${id}`}>{label}</a>)}</nav><div className="footer-info"><a href={b.tel}>{b.phone}</a><p>{b.locality}, Karnataka</p><p>Daily · {b.hours}</p></div></div><div className="footer-bottom"><p>© 2026 {b.name}. All rights reserved.</p><a href="#home">BACK TO TOP <ArrowUpRight size={14}/></a></div><div className="footer-wordmark" aria-hidden="true">MR.CLOTHING<span>®</span></div></footer><MobileActions/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
 </>}
